/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parkingaduanas.igu;

/**
 *
 * @author enzo
 */
public class Ventana_Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_Principal.class.getName());

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        lbl_fotoAduanas = new javax.swing.JLabel();
        btn_verEstacionamiento = new javax.swing.JButton();
        btn_GestionImporAutos = new javax.swing.JButton();
        btn_GestionFuncionarios = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_fotoAduanas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_web1.png"))); // NOI18N

        btn_verEstacionamiento.setText("VER ESTACIONAMIENTO");
        btn_verEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verEstacionamientoActionPerformed(evt);
            }
        });

        btn_GestionImporAutos.setText("GESTIONAR IMPORTADORES / VEHICULOS");

        btn_GestionFuncionarios.setText("GESTIONAR FUNCIONARIOS");
        btn_GestionFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GestionFuncionariosActionPerformed(evt);
            }
        });

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_fotoAduanas))
                    .addGroup(pnl_menuLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_GestionImporAutos)
                            .addComponent(btn_verEstacionamiento)
                            .addComponent(btn_GestionFuncionarios)
                            .addComponent(btn_salir))))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addComponent(lbl_fotoAduanas)
                .addGap(31, 31, 31)
                .addComponent(btn_verEstacionamiento)
                .addGap(29, 29, 29)
                .addComponent(btn_GestionImporAutos)
                .addGap(27, 27, 27)
                .addComponent(btn_GestionFuncionarios)
                .addGap(18, 18, 18)
                .addComponent(btn_salir)
                .addGap(0, 288, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verEstacionamientoActionPerformed
        // TODO add your handling code here:
        Ventana_Parking ventana_parking = new Ventana_Parking();
        ventana_parking.setVisible(true);
        ventana_parking.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_verEstacionamientoActionPerformed

    private void btn_GestionFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GestionFuncionariosActionPerformed
        // TODO add your handling code here:
        Ventana_Funcionarios ventana_funcionarios = new Ventana_Funcionarios();
        ventana_funcionarios.setVisible(true);
        ventana_funcionarios.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_GestionFuncionariosActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GestionFuncionarios;
    private javax.swing.JButton btn_GestionImporAutos;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_verEstacionamiento;
    private javax.swing.JLabel lbl_fotoAduanas;
    private javax.swing.JPanel pnl_menu;
    // End of variables declaration//GEN-END:variables
}
