/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parkingaduanas.igu;

/**
 *
 * @author Brian
 */
public class Ventana_Funcionarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_Funcionarios.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Ventana_Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logoAduana = new javax.swing.JLabel();
        pnl_acciones = new javax.swing.JPanel();
        cmbox_funcionarios = new javax.swing.JComboBox<>();
        btn_verInfoFunc = new javax.swing.JButton();
        btn_eliminarFunc = new javax.swing.JButton();
        pnl_accionesAniadirFuncionarios = new javax.swing.JPanel();
        btn_limpiarfunc = new javax.swing.JButton();
        btn_salirdefunc = new javax.swing.JButton();
        btn_aniadirfunc = new javax.swing.JButton();
        pnl_aniadirFuncionarios = new javax.swing.JPanel();
        lbl_aniadirFuncionarios = new javax.swing.JLabel();
        lbl_ingresarNombre = new javax.swing.JLabel();
        lbl_ingresarApellido = new javax.swing.JLabel();
        lbl_ingresarCorreo = new javax.swing.JLabel();
        lbl_ingresarCI = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        txt_AniadirNombre = new javax.swing.JTextField();
        txt_AniadirApellido = new javax.swing.JTextField();
        txt_AniadirCorreo = new javax.swing.JTextField();
        txt_AniadirTelefono = new javax.swing.JTextField();
        txt_AniadirCI = new javax.swing.JTextField();
        pnl_infoFuncionario = new javax.swing.JPanel();
        lbl_infoFuncionario = new javax.swing.JLabel();
        lbl_mostarNombre = new javax.swing.JLabel();
        lbl_mostarApellido = new javax.swing.JLabel();
        lbl_mostarCorreo = new javax.swing.JLabel();
        lbl_mostarCI = new javax.swing.JLabel();
        lbl_mostarTelefono = new javax.swing.JLabel();
        txt_mostrarNombre = new javax.swing.JTextField();
        txt_mostrarApellido = new javax.swing.JTextField();
        txt_mostrarCorreo = new javax.swing.JTextField();
        txt_mostrarTelefono = new javax.swing.JTextField();
        txt_mostrarCI = new javax.swing.JTextField();

        lbl_logoAduana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_web1.png"))); // NOI18N

        pnl_acciones.setBorder(javax.swing.BorderFactory.createTitledBorder("VER INFORMACION DE FUNCIONARIOS"));
        pnl_acciones.setPreferredSize(new java.awt.Dimension(200, 200));

        cmbox_funcionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbox_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbox_funcionariosActionPerformed(evt);
            }
        });

        btn_verInfoFunc.setText("VER INFORMACION");

        btn_eliminarFunc.setText("ELIMINAR FUNCIONARIO");

        pnl_accionesAniadirFuncionarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Funcionario"));
        pnl_accionesAniadirFuncionarios.setPreferredSize(new java.awt.Dimension(200, 200));

        btn_limpiarfunc.setText("LIMPIAR DATOS");
        btn_limpiarfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarfuncActionPerformed(evt);
            }
        });

        btn_salirdefunc.setText("Salir al inicio");
        btn_salirdefunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirdefuncActionPerformed(evt);
            }
        });

        btn_aniadirfunc.setText("AÑADIR FUNCIONARIO");

        javax.swing.GroupLayout pnl_accionesAniadirFuncionariosLayout = new javax.swing.GroupLayout(pnl_accionesAniadirFuncionarios);
        pnl_accionesAniadirFuncionarios.setLayout(pnl_accionesAniadirFuncionariosLayout);
        pnl_accionesAniadirFuncionariosLayout.setHorizontalGroup(
            pnl_accionesAniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_accionesAniadirFuncionariosLayout.createSequentialGroup()
                .addGroup(pnl_accionesAniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_accionesAniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnl_accionesAniadirFuncionariosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btn_aniadirfunc, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addGroup(pnl_accionesAniadirFuncionariosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btn_limpiarfunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl_accionesAniadirFuncionariosLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_salirdefunc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnl_accionesAniadirFuncionariosLayout.setVerticalGroup(
            pnl_accionesAniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_accionesAniadirFuncionariosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_aniadirfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_limpiarfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_salirdefunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_accionesLayout = new javax.swing.GroupLayout(pnl_acciones);
        pnl_acciones.setLayout(pnl_accionesLayout);
        pnl_accionesLayout.setHorizontalGroup(
            pnl_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_accionesLayout.createSequentialGroup()
                .addGroup(pnl_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_accionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnl_accionesAniadirFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_accionesLayout.createSequentialGroup()
                        .addGroup(pnl_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_eliminarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_accionesLayout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(cmbox_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl_accionesLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btn_verInfoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_accionesLayout.setVerticalGroup(
            pnl_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_accionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cmbox_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_verInfoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(pnl_accionesAniadirFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbl_aniadirFuncionarios.setText("AÑADIR FUNCIONARIO");

        lbl_ingresarNombre.setText("INGRESE SU NOMBRE: ");

        lbl_ingresarApellido.setText("INGRESE SU APELLIDO: ");

        lbl_ingresarCorreo.setText("INGRESE SU CORREO ELECTRONICO: ");

        lbl_ingresarCI.setText("INGRESE SU C.I: ");

        lbl_telefono.setText("INGRESE SU TELEFONO: ");

        txt_AniadirNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AniadirNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_aniadirFuncionariosLayout = new javax.swing.GroupLayout(pnl_aniadirFuncionarios);
        pnl_aniadirFuncionarios.setLayout(pnl_aniadirFuncionariosLayout);
        pnl_aniadirFuncionariosLayout.setHorizontalGroup(
            pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aniadirFuncionariosLayout.createSequentialGroup()
                .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_aniadirFuncionariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_aniadirFuncionarios))
                    .addGroup(pnl_aniadirFuncionariosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_aniadirFuncionariosLayout.createSequentialGroup()
                                .addComponent(lbl_ingresarNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_AniadirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_aniadirFuncionariosLayout.createSequentialGroup()
                                .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ingresarCI)
                                    .addComponent(lbl_ingresarCorreo)
                                    .addComponent(lbl_telefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_AniadirCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_AniadirTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_AniadirCI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_aniadirFuncionariosLayout.createSequentialGroup()
                                .addComponent(lbl_ingresarApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_AniadirApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(157, 157, 157))
        );
        pnl_aniadirFuncionariosLayout.setVerticalGroup(
            pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aniadirFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_aniadirFuncionarios)
                .addGap(18, 18, 18)
                .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_AniadirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingresarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ingresarApellido)
                    .addComponent(txt_AniadirApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_AniadirTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_telefono))
                .addGap(18, 18, 18)
                .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ingresarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_AniadirCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnl_aniadirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_ingresarCorreo)
                    .addComponent(txt_AniadirCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lbl_infoFuncionario.setText("INFORMACION DE FUNCIONARIO:");

        lbl_mostarNombre.setText("NOMBRE:");

        lbl_mostarApellido.setText("APELLIDO:");

        lbl_mostarCorreo.setText("CORREO ELECTRONICO:");

        lbl_mostarCI.setText("CEDULA DE IDENTIDAD:");

        lbl_mostarTelefono.setText("TELEFONO:");

        txt_mostrarNombre.setEditable(false);
        txt_mostrarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mostrarNombreActionPerformed(evt);
            }
        });

        txt_mostrarApellido.setEditable(false);

        txt_mostrarCorreo.setEditable(false);

        txt_mostrarTelefono.setEditable(false);

        txt_mostrarCI.setEditable(false);

        javax.swing.GroupLayout pnl_infoFuncionarioLayout = new javax.swing.GroupLayout(pnl_infoFuncionario);
        pnl_infoFuncionario.setLayout(pnl_infoFuncionarioLayout);
        pnl_infoFuncionarioLayout.setHorizontalGroup(
            pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_infoFuncionario))
                    .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                                .addComponent(lbl_mostarNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_mostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                                .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                                            .addComponent(lbl_mostarApellido)
                                            .addGap(71, 71, 71))
                                        .addComponent(lbl_mostarCI, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lbl_mostarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_mostarTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_mostrarTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(txt_mostrarCorreo)
                                    .addComponent(txt_mostrarCI)
                                    .addComponent(txt_mostrarApellido))))))
                .addGap(282, 282, 282))
        );
        pnl_infoFuncionarioLayout.setVerticalGroup(
            pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_infoFuncionario)
                .addGap(18, 18, 18)
                .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                        .addComponent(lbl_mostarNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_mostarApellido)
                            .addComponent(txt_mostrarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mostrarCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_mostarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_mostarCorreo)
                            .addComponent(txt_mostrarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_infoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_mostarTelefono)
                            .addComponent(txt_mostrarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(pnl_infoFuncionarioLayout.createSequentialGroup()
                        .addComponent(txt_mostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_acciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_infoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_aniadirFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_logoAduana)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_logoAduana, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_infoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_aniadirFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbox_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbox_funcionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbox_funcionariosActionPerformed

    private void txt_AniadirNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AniadirNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AniadirNombreActionPerformed

    private void txt_mostrarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mostrarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mostrarNombreActionPerformed

    private void btn_salirdefuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirdefuncActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_salirdefuncActionPerformed

    private void btn_limpiarfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarfuncActionPerformed
        // BOTON LIMPIAR INFORMACION
        txt_AniadirApellido.setText("");
        txt_AniadirCorreo.setText("");
        txt_AniadirCI.setText("");
        txt_AniadirNombre.setText("");
        txt_AniadirTelefono.setText("");
    }//GEN-LAST:event_btn_limpiarfuncActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aniadirfunc;
    private javax.swing.JButton btn_eliminarFunc;
    private javax.swing.JButton btn_limpiarfunc;
    private javax.swing.JButton btn_salirdefunc;
    private javax.swing.JButton btn_verInfoFunc;
    private javax.swing.JComboBox<String> cmbox_funcionarios;
    private javax.swing.JLabel lbl_aniadirFuncionarios;
    private javax.swing.JLabel lbl_infoFuncionario;
    private javax.swing.JLabel lbl_ingresarApellido;
    private javax.swing.JLabel lbl_ingresarCI;
    private javax.swing.JLabel lbl_ingresarCorreo;
    private javax.swing.JLabel lbl_ingresarNombre;
    private javax.swing.JLabel lbl_logoAduana;
    private javax.swing.JLabel lbl_mostarApellido;
    private javax.swing.JLabel lbl_mostarCI;
    private javax.swing.JLabel lbl_mostarCorreo;
    private javax.swing.JLabel lbl_mostarNombre;
    private javax.swing.JLabel lbl_mostarTelefono;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JPanel pnl_acciones;
    private javax.swing.JPanel pnl_accionesAniadirFuncionarios;
    private javax.swing.JPanel pnl_aniadirFuncionarios;
    private javax.swing.JPanel pnl_infoFuncionario;
    private javax.swing.JTextField txt_AniadirApellido;
    private javax.swing.JTextField txt_AniadirCI;
    private javax.swing.JTextField txt_AniadirCorreo;
    private javax.swing.JTextField txt_AniadirNombre;
    private javax.swing.JTextField txt_AniadirTelefono;
    private javax.swing.JTextField txt_mostrarApellido;
    private javax.swing.JTextField txt_mostrarCI;
    private javax.swing.JTextField txt_mostrarCorreo;
    private javax.swing.JTextField txt_mostrarNombre;
    private javax.swing.JTextField txt_mostrarTelefono;
    // End of variables declaration//GEN-END:variables
}
