/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parkingaduanas.igu;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Brian
 */
public class Ventana_AniadirDatosVehiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_AniadirDatosVehiculo.class.getName());
    private File imagenSeleccionada;
    
    /**
     * Creates new form Ventana_AniadirDatosVehiculo
     */
    public Ventana_AniadirDatosVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_DatosVehiculos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_seleccionarFoto = new javax.swing.JButton();
        lbl_Foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_DatosVehiculos.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos Vehiculos"));

        jLabel1.setText("Ingresar Foto Vehiculo");

        btn_seleccionarFoto.setText("SELECCIONAR FOTO");
        btn_seleccionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarFotoActionPerformed(evt);
            }
        });

        lbl_Foto.setText("jLabel2");

        javax.swing.GroupLayout pnl_DatosVehiculosLayout = new javax.swing.GroupLayout(pnl_DatosVehiculos);
        pnl_DatosVehiculos.setLayout(pnl_DatosVehiculosLayout);
        pnl_DatosVehiculosLayout.setHorizontalGroup(
            pnl_DatosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DatosVehiculosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnl_DatosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Foto)
                    .addGroup(pnl_DatosVehiculosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_seleccionarFoto)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnl_DatosVehiculosLayout.setVerticalGroup(
            pnl_DatosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DatosVehiculosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnl_DatosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_seleccionarFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Foto)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_DatosVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_DatosVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarFotoActionPerformed
        // TODO add your handling code here: JFileChooser fileChooser = new JFileChooser();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar imagen");

        // Filtro para mostrar solo imágenes
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes (JPG, PNG, JPEG)", "jpg", "png", "jpeg"));

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
        imagenSeleccionada = fileChooser.getSelectedFile();
        
        // Mostrar la imagen en el JLabel
        ImageIcon icono = new ImageIcon(imagenSeleccionada.getAbsolutePath());
        Image imagen = icono.getImage().getScaledInstance(
                lbl_Foto.getWidth(), lbl_Foto.getHeight(), Image.SCALE_SMOOTH);
        lbl_Foto.setIcon(new ImageIcon(imagen));
        
        }
        
    }//GEN-LAST:event_btn_seleccionarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana_AniadirDatosVehiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_seleccionarFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Foto;
    private javax.swing.JPanel pnl_DatosVehiculos;
    // End of variables declaration//GEN-END:variables
}
