/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ventanaprincipal;

/**
 *
 * @author enzo
 */
public class Ventana_Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_Menu.class.getName());

    /**
     * Creates new form Ventana_Menu
     */
    public Ventana_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_logos = new javax.swing.JLabel();
        btn_verEstacionamiento = new javax.swing.JButton();
        btn_gestionarImportadores1 = new javax.swing.JButton();
        btn_gestionarFuncionarios = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_gestionarVehiculos = new javax.swing.JButton();
        btn_verEstacionamiento1 = new javax.swing.JButton();
        btn_verEstacionamiento2 = new javax.swing.JButton();
        btn_verEstacionamiento3 = new javax.swing.JButton();
        btn_verEstacionamiento4 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADUANAS");
        setFocusable(false);

        img_logos.setIcon(new javax.swing.ImageIcon("/home/enzo/Descargas/logo_web 1.png")); // NOI18N

        btn_verEstacionamiento.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        btn_verEstacionamiento.setText("Ver Estacionamiento");

        btn_gestionarImportadores1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        btn_gestionarImportadores1.setText("Gestionar Importadores");

        btn_gestionarFuncionarios.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        btn_gestionarFuncionarios.setText("Gestionar Funcionarios");
        btn_gestionarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestionarFuncionariosActionPerformed(evt);
            }
        });

        btn_salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_gestionarVehiculos.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        btn_gestionarVehiculos.setText("Gestionar Vehiculos");

        btn_verEstacionamiento1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        btn_verEstacionamiento1.setText("VER PÁGINA AUTOBLOG URUGUAY");

        btn_verEstacionamiento2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        btn_verEstacionamiento2.setText("VER CONSIGNA OGLIGATORIO");

        btn_verEstacionamiento3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        btn_verEstacionamiento3.setText("VER PÁGINA ADUANA URUGUAY");

        btn_verEstacionamiento4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        btn_verEstacionamiento4.setText("INFORMACIÓN DEL PROGRAMA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(img_logos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_gestionarFuncionarios)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_verEstacionamiento)
                                .addComponent(btn_gestionarVehiculos)
                                .addComponent(btn_gestionarImportadores1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_verEstacionamiento3)
                            .addComponent(btn_verEstacionamiento1)
                            .addComponent(btn_verEstacionamiento2)
                            .addComponent(btn_verEstacionamiento4))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(img_logos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_verEstacionamiento)
                        .addGap(18, 18, 18)
                        .addComponent(btn_gestionarImportadores1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_gestionarVehiculos)
                        .addGap(18, 18, 18)
                        .addComponent(btn_gestionarFuncionarios)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salir)
                    .addComponent(btn_verEstacionamiento1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_verEstacionamiento3)
                .addGap(10, 10, 10)
                .addComponent(btn_verEstacionamiento2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_verEstacionamiento4)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // 
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_gestionarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestionarFuncionariosActionPerformed

        
    }//GEN-LAST:event_btn_gestionarFuncionariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gestionarFuncionarios;
    private javax.swing.JButton btn_gestionarImportadores1;
    private javax.swing.JButton btn_gestionarVehiculos;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_verEstacionamiento;
    private javax.swing.JButton btn_verEstacionamiento1;
    private javax.swing.JButton btn_verEstacionamiento2;
    private javax.swing.JButton btn_verEstacionamiento3;
    private javax.swing.JButton btn_verEstacionamiento4;
    private javax.swing.JLabel img_logos;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
